### PR TITLE
Error manager

### PR DESCRIPTION
**Pull request by MatejMagat305**
this is only sugest (because I have lot of useless constants) how is posible solve errors
(again you are free, I am only share ideas with you ...)

### CODE REVIEW

**Comment by Zyko0** [comment]
Thanks!

This is a lot of content, I can't check everything, but I'm fine to merge on the new branch I created (I just swapped the target of your PR: https://github.com/Zyko0/go-opencl/tree/feature/constants-paths-definitions)
Then I'll refactor it a bit!

Tell me when you're okay to merge this PR on the branch!

**Comment by MatejMagat305** [comment]
> Thanks!
> 
> This is a lot of content, I can't check everything, but I'm fine to merge on the new branch I created (I just swapped the target of your PR: https://github.com/Zyko0/go-opencl/tree/feature/constants-paths-definitions) Then I'll refactor it a bit!
> 
> Tell me when you're okay to merge this PR on the branch!

do not hurry, I will not remove it ..., I will finish my fork (of blackcl), I hope I can use some your ideas (I will mention you as inspiration, ok? your will provide more and I want to excessive it ...)

**Comment by MatejMagat305** [comment]
if I can ask, I see a lot of uint, would it be uint32?
And I have biggest sugest, I create lowest level (from your) https://github.com/opencl-pure/triple-opencl, could I fill package "midle" with your wrapper method(your fork, but calling "pure" package"? 

of couse there is package "high" with my high level wrapper too...
I would like add you as second owner, could we provide together? 
It still contains errors, but it will be amasing options to choose ...

**Comment by Zyko0** [comment]
> if I can ask, I see a lot of uint, would it be uint32?

No particular reason, except sometimes one or the other would give me an error, so I figured some of these by trial and error!

> could I fill package "midle" with your wrapper method(your fork, but calling "pure" package"?

Of course, please feel free to use this base as you wish!

> I would like add you as second owner, could we provide together?

I stopped working on openCL at the moment and have no active project using it anymore, so I kinda let it on the side for now.
I don't think I'll have the bandwidth to work on openCL more at the moment unfortunately!

**Comment by MatejMagat305** [comment]
> > if I can ask, I see a lot of uint, would it be uint32?
> 
> No particular reason, except sometimes one or the other would give me an error, so I figured some of these by trial and error!
> 
> > could I fill package "midle" with your wrapper method(your fork, but calling "pure" package"?
> 
> Of course, please fill free to use this base as you wish!
> 
> > I would like add you as second owner, could we provide together?
> 
> I stopped working on openCL at the moment and have no active project using it anymore, so I kinda let it on the side for now. I don't think I'll have the bandwidth to work on openCL more at the moment unfortunately!

ok, thank you

**Pull request closed without merging**
