### PR TITLE
mising import and multiple paths

### PR DESCRIPTION
**Pull request by MatejMagat305**
I will give you some idea from my, ok?

### CODE REVIEW

**Comment by Zyko0** [comment]
> I will give you some idea from my, ok?

Sure, thank you!
I'd like to have the reference written near the paths lists as a comment just so we remember where it's from! (https://github.com/krrishnarraj/libopencl-stub)

About the code itself, I would prefer not to have the extra getLib function, and getPaths returning an empty slice (but rather an error)

I have the intuition that `libOpenCL.so` should be put on top of each slice also, because it's probably going to be resolved most of the time, skipping irrelevant loading attempts.

We can merge as-is, and I can refactor it a little right after if you prefer!

**Comment by MatejMagat305** [comment]
> Sure, thank you! I'd like to have the reference written near the paths lists as a comment just so we remember where it's from! (https://github.com/krrishnarraj/libopencl-stub)
> 
> About the code itself, I would prefer not to have the extra getLib function, and getPaths returning an empty slice (but rather an error)
> 
> I have the intuition that `libOpenCL.so` should be put on top of each slice also, because it's probably going to be resolved most of the time, skipping irrelevant loading attempts.
> 
> We can merge as-is, and I can refactor it a little right after if you prefer!

you are free, I am only share ideas with you ... and you are right https://github.com/krrishnarraj/libopencl-stub is suitable to remember ...

**Comment by Zyko0** [comment]
Is this one superseeded by https://github.com/Zyko0/go-opencl/pull/2?
If so, we can close this one

**Comment by MatejMagat305** [comment]
> Is this one superseeded by #2? If so, we can close this one

yes

**Pull request closed without merging**
